version: '3'

services:
    db:
      image: postgres:12-alpine
      volumes:
        - pgdata:/var/lib/postgresql/data
      expose:
        - 5432
      environment:
        POSTGRES_HOST: db
        POSTGRES_PORT: 5432
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: postgres

    app:
      build:
        context: .
        args:
          PIPENV_FLAGS: --dev
      env_file: .env
      volumes:
        - .:/app
      depends_on:
        - db
      environment:
        POSTGRES_HOST: db
      stdin_open: true 
      tty: true

volumes:
  pgdata: