"""initial

Revision ID: 93157c44fddd
Revises: 
Create Date: 2023-04-29 18:26:56.533300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93157c44fddd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weather',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('city', sa.VARCHAR(), nullable=False),
    sa.Column('temperature', sa.INTEGER(), nullable=False),
    sa.Column('wind_speed', sa.FLOAT(), nullable=True),
    sa.Column('humidity', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=False), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weather')
    # ### end Alembic commands ###
